<%@ page language="java" contentType="text/html; charset=UTF-8"
    pageEncoding="UTF-8"%>
<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
<title>Insert title here</title>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/jQuery-rwdImageMaps/1.6/jquery.rwdImageMaps.js"></script>
  <script type="text/javascript">
  $(function() {
	  $('img[usemap]').rwdImageMaps();
	  $('area').on('click', function () {
		alert($(this).attr('alt') + ' 입니다.');
	  });
	});
  </script>
  <style type="text/css">
  img { width: 100%; }
  </style>
</head>
<body>
 <section>
    <!-- Image Map Generated by http://www.image-map.net/ -->
    <img src="https://upload.wikimedia.org/wikipedia/commons/c/c3/Flag_of_France.svg" usemap="#image-map">
  
    <map name="image-map">
      <area alt="파란색" href="#" title="파란색" coords="1,0,300,599" shape="rect">
      <area alt="흰색" href="#" title="흰색" coords="302,0,600,599" shape="rect">
      <area alt="빨간색" href="#" title="빨간색" coords="602,0,900,599" shape="rect">
    </map>
  </section>
</body>
</html>